apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-0
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "*"
    routes:
      - matchers:
        - exact: /api/v1/healthz
        options:
          prefixRewrite: /check/healthz
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-1
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "aaa"
      - "aab"
      - "aac"
    routes:
      - matchers:
          - exact: /api/v1/create
        options:
          prefixRewrite: /create
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-2
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "bba"
      - "bbb"
      - "bbc"
    routes:
      - matchers:
          - exact: /api/v1/tasks
        options:
          prefixRewrite: /
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-3
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "cca"
      - "ccb"
      - "ccc"
    routes:
      - matchers:
          - prefix: /api/v1/tasks/
        options:
          prefixRewrite: /
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-4
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "dda"
      - "ddb"
      - "ddc"
    routes:
      - matchers:
          - prefix: /api/v1/test/1
        options:
          prefixRewrite: /test/1
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-5
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "eea"
      - "eeb"
      - "eec"
    routes:
      - matchers:
          - prefix: /api/v1/test/2
        options:
          prefixRewrite: /test/2
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-6
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "ffa"
      - "ffb"
      - "ffc"
    routes:
      - matchers:
          - prefix: /api/v1/test/3
        options:
          prefixRewrite: /test/3
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-7
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "gga"
      - "ggb"
      - "ggc"
    routes:
      - matchers:
          - prefix: /api/v1/test/4
        options:
          prefixRewrite: /test/4
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-8
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "hha"
      - "hhb"
      - "hhc"
    routes:
      - matchers:
          - prefix: /api/v1/test/5
        options:
          prefixRewrite: /test/5
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-9
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "iia"
      - "iib"
      - "iic"
    routes:
      - matchers:
          - prefix: /api/v1/test/6
        options:
          prefixRewrite: /test/6
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-10
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "jja"
      - "jjb"
      - "jjc"
    routes:
      - matchers:
          - prefix: /api/v1/test/7
        options:
          prefixRewrite: /test/7
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-11
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "kka"
      - "kkb"
      - "kkc"
    routes:
      - matchers:
          - prefix: /api/v1/test/8
        options:
          prefixRewrite: /test/8
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-12
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "lla"
      - "llb"
      - "llc"
    routes:
      - matchers:
          - prefix: /api/v1/test/9
        options:
          prefixRewrite: /test/9
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-13
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "mma"
      - "mmb"
      - "mmc"
    routes:
      - matchers:
          - prefix: /api/v1/test/10
        options:
          prefixRewrite: /test/10
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-14
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "nna"
      - "nnb"
      - "nnc"
    routes:
      - matchers:
          - prefix: /api/v1/test/11
        options:
          prefixRewrite: /test/11
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-15
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "ooa"
      - "oob"
      - "ooc"
    routes:
      - matchers:
          - prefix: /api/v1/test/12
        options:
          prefixRewrite: /test/12
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-16
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "ppa"
      - "ppb"
      - "ppc"
    routes:
      - matchers:
          - prefix: /api/v1/test/13
        options:
          prefixRewrite: /test/13
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-17
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "qqa"
      - "qqb"
      - "qqc"
    routes:
      - matchers:
          - prefix: /api/v1/test/14
        options:
          prefixRewrite: /test/14
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-18
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "rra"
      - "rrb"
      - "rrc"
    routes:
      - matchers:
          - prefix: /api/v1/test/15
        options:
          prefixRewrite: /test/15
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:  
  name: default-19
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "ssa"
      - "ssb"
      - "ssc"
    routes:
      - matchers:
          - prefix: /api/v1/test/16
        options:
          prefixRewrite: /test/16
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-20
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "tta"
      - "ttb"
      - "ttc"
    routes:
      - matchers:
          - prefix: /api/v1/test/17
        options:
          prefixRewrite: /test/17
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-21
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "uua"
      - "uub"
      - "uuc"
    routes:
      - matchers:
          - prefix: /api/v1/test/18
        options:
          prefixRewrite: /test/18
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-22
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "vva"
      - "vvb"
      - "vvc"
    routes:
      - matchers:
          - prefix: /api/v1/test/19
        options:
          prefixRewrite: /test/19
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-23
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "wwa"
      - "wwb"
      - "wwc"
    routes:
      - matchers:
          - prefix: /api/v1/test/20
        options:
          prefixRewrite: /test/20
        routeAction:
          single:
            upstream:
              name: default-nineteen-vs-8080 
              namespace: gloo-system